#############################################################################
# GitHub Action to bump license year in all projects
#
# Workflow starts every new year.
#
#############################################################################
name: "Bump license year in all project"
  workflow_dispatch:
permissions:
  contents: write
  pull-requests: write
jobs:
  bump:
    name: Bump license year in all projects
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the latest code
        uses: actions/checkout@v2
        with:
          token: ${{ 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 }}
      - name: Set Current Year
        id: CURRENT_YEAR
        run: |
          echo "::set-output name=year::$(date +'%Y')"
      - name: Modify File
        run: |
          ./.ci/bump-license-year-in-all-projects.sh $(expr ${{ env.YEAR }} - 1) ${{ env.YEAR }} .
        env:
          YEAR: ${{ 2023 }}
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        env:
          YEAR: ${{ steps.CURRENT_YEAR.outputs.year }}
        with:
          commit-message: "minor: Bump year in all projects to ${{ env.YEAR }}"
          committer: github-actions[bot] 
          <github-actions[bot]@users.noreply.github.com>
          author: github-actions[bot] 
          <github-actions[bot]@users.noreply.github.com>
          branch: bump-year
          delete-branch: true
          body: "minor: Bump year in all projects to ${{ env.YEAR }}"
          title: "minor: Bump year in all projects to ${{ env.YEAR }}"
          token: ${{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 }}
